// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeAgGiF-M3Je4DUpKT59O_lvgB3uDUvik',
    appId: '1:851904795750:web:eb6f94b1e65288e42289a7',
    messagingSenderId: '851904795750',
    projectId: 'gold-silver-rates-app-by-gc',
    authDomain: 'gold-silver-rates-app-by-gc.firebaseapp.com',
    storageBucket: 'gold-silver-rates-app-by-gc.firebasestorage.app',
    measurementId: 'G-HDESC5F5Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdsgaE-nyHdsk_XAUKf09Ck6xlxuKQLHs',
    appId: '1:851904795750:android:435dc3a51cadc5892289a7',
    messagingSenderId: '851904795750',
    projectId: 'gold-silver-rates-app-by-gc',
    storageBucket: 'gold-silver-rates-app-by-gc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs4eU8OcoS1AwRLmrqsQVUSg5UwODXbqI',
    appId: '1:851904795750:ios:f7e56d4344795c172289a7',
    messagingSenderId: '851904795750',
    projectId: 'gold-silver-rates-app-by-gc',
    storageBucket: 'gold-silver-rates-app-by-gc.firebasestorage.app',
    iosBundleId: 'com.example.gcGoldRates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs4eU8OcoS1AwRLmrqsQVUSg5UwODXbqI',
    appId: '1:851904795750:ios:f7e56d4344795c172289a7',
    messagingSenderId: '851904795750',
    projectId: 'gold-silver-rates-app-by-gc',
    storageBucket: 'gold-silver-rates-app-by-gc.firebasestorage.app',
    iosBundleId: 'com.example.gcGoldRates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeAgGiF-M3Je4DUpKT59O_lvgB3uDUvik',
    appId: '1:851904795750:web:8015c6a212adea922289a7',
    messagingSenderId: '851904795750',
    projectId: 'gold-silver-rates-app-by-gc',
    authDomain: 'gold-silver-rates-app-by-gc.firebaseapp.com',
    storageBucket: 'gold-silver-rates-app-by-gc.firebasestorage.app',
    measurementId: 'G-8R903EXBF4',
  );
}
